add notify script options

diff --git a/files/natmap.init b/files/natmap.init
--- a/files/natmap.init
+++ b/files/natmap.init
@@ -113,6 +113,11 @@ validate_section_natmap() {
 		'clt_web_port:and(port, min(1))' \
 		'clt_username:string' \
 		'clt_password:string' \
+		'notify_enable:bool:0' \
+		'notify_script:file' \
+		'notify_tokens:list(string)' \
+		'notify_custom_domain:hostname' \
+		'notify_text:string' \
 		'custom_script:file'
 }
 
@@ -171,6 +176,15 @@ natmap_instance() {
 			json_add_string ip "$forward_target"
 			procd_append_param env "REFRESH_PARAM=$(json_dump)"
 		fi
+	fi
+
+	if [ "$notify_enable" = 1 ]; then
+		procd_append_param env "NOTIFY=$notify_script"
+		json_init
+		json_add_string custom_domain "$notify_custom_domain"
+		json_add_string text "$notify_text"
+		json_add_string tokens "$notify_tokens"
+		procd_append_param env "NOTIFY_PARAM=$(json_dump)"
 	fi
 
 	[ -n "${custom_script}" ] && procd_append_param env "CUSTOM_SCRIPT=${custom_script}"
@@ -288,10 +302,16 @@ launcher() {
 	elif [ "$refresh" = 0 ]; then
 		unset clt_script
 	fi
+	## notify
+	if   [ "$notify_enable" = 1 ]; then
+		[ -x "$notify_script" ] || { >&2 echo "$(basename $0): section $1 option notify_script '$notify_script' is empty or non-executable"; let error++; }
+	elif [ "$notify_enable" = 0 ]; then
+		unset notify_script
+	fi
 
 	# review
 	[ -n "$NATMAP_DEBUG" ] && {
-		local v ucivv="enable interval stun_server http_server comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward forward_mode natloopback forward_target forward_port refresh clt_script clt_scheme clt_web_port clt_username clt_password custom_script"
+		local v ucivv="enable interval stun_server http_server comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward forward_mode natloopback forward_target forward_port refresh clt_script clt_scheme clt_web_port clt_username clt_password notify_enable notify_script notify_tokens notify_custom_domain notify_text custom_script"
 		for v in $ucivv; do eval "echo $1 $v=\'\$$v\'"; done # ash not support ${!v}
 	}
 	[ "$error" -gt 0 ] && return 1
