natmap: uci options change
forward_mode --> forward
forward_method --> forward_mode
Signed-off-by: Anya Lin <hukk1996@gmail.com>

diff --git a/net/natmap/files/natmap.init b/net/natmap/files/natmap.init
--- a/net/natmap/files/natmap.init
+++ b/net/natmap/files/natmap.init
@@ -102,8 +102,8 @@ validate_section_natmap() {
 		'family:or("ipv4", "ipv6"):ipv4' \
 		'bind_ifname:network' \
 		'port:and(port, min(1))' \
-		'forward_mode:bool:0' \
-		'forward_method:or("dnat", "via"):via' \
+		'forward:bool:0' \
+		'forward_mode:or("dnat", "via"):via' \
 		'natloopback:bool:1' \
 		'forward_target:ipaddr(1)' \
 		'forward_port:port' \
@@ -150,10 +150,10 @@ natmap_instance() {
 		network_get_device ifname "$DEF_WAN6" && procd_append_param netdev "$ifname"
 	}
 
-	[ "$forward_mode" = 1 -a "$forward_method" = "via" -a -n "${forward_target}" ] && procd_append_param command -t "$forward_target" -p "$forward_port"
+	[ "$forward" = 1 -a "$forward_mode" = "via" -a -n "${forward_target}" ] && procd_append_param command -t "$forward_target" -p "$forward_port"
 
 	procd_set_param env "SECTIONID=$1"
-	[ "$forward_mode" = 1 -a "$forward_method" = "dnat" -a "$forward_port" = 0 ] && procd_append_param env "REFRESH=1"
+	[ "$forward" = 1 -a "$forward_mode" = "dnat" -a "$forward_port" = 0 ] && procd_append_param env "REFRESH=1"
 
 	[ -n "${notify_script}" ] && procd_append_param env "NOTIFY_SCRIPT=${notify_script}"
 	procd_append_param command -e /usr/lib/natmap/update.sh
@@ -165,7 +165,7 @@ natmap_instance() {
 	procd_open_data
 	# configure firewall
 	json_add_array firewall
-		if [ "$forward_mode" = 1 -a "$forward_method" = "dnat" ]; then
+		if [ "$forward" = 1 -a "$forward_mode" = "dnat" ]; then
 			json_add_object ''
 			json_add_string type redirect
 			json_add_string target DNAT
@@ -183,7 +183,7 @@ natmap_instance() {
 			json_add_boolean reflection $natloopback
 			json_close_object
 		fi
-		if [ "$forward_mode" = 1 -a "$forward_method" = "via" -o "$forward_mode" = 0 ]; then
+		if [ "$forward" = 1 -a "$forward_mode" = "via" -o "$forward" = 0 ]; then
 			json_add_object ''
 			json_add_string type rule
 			json_add_string target ACCEPT
@@ -243,9 +243,9 @@ launcher() {
 	esac
 	[ -z "$bind_ip" ] && >&2 echo "$(basename $0): section $1 bind_ip parsing failed, there may be no $family network connection" && let error++
 	[ -z "$port" ] && err_msg__empty $1 port && let error++
-	if   [ "$forward_mode" = 1 ]; then
-		[ "$forward_method" = "dnat" -a "$family" = "ipv6" ] && >&2 echo "$(basename $0): section $1 option forward_method 'dnat' not support under IPv6" && let error++
-		[ "$forward_method" != "dnat" ] && natloopback=0
+	if   [ "$forward" = 1 ]; then
+		[ "$forward_mode" = "dnat" -a "$family" = "ipv6" ] && >&2 echo "$(basename $0): section $1 option forward_mode 'dnat' not support under IPv6" && let error++
+		[ "$forward_mode" != "dnat" ] && natloopback=0
 		if [ -n "$forward_target" ]; then
 			[ -n "$(echo $forward_target|grep -E "^127(\.\d+){3}")" -o "$forward_target" = "::1" ] && forward_target="$lan_addr"
 			[ -n "$(echo $forward_target|grep -E "^0(\.\d+){3}")" -o "$forward_target" = "::" ] && forward_target="$bind_ip"
@@ -258,13 +258,13 @@ launcher() {
 			err_msg__empty $1 forward_target; let error++
 		fi
 		[ -z "$forward_port" ] && err_msg__empty $1 forward_port && let error++
-	elif [ "$forward_mode" = 0 ]; then
+	elif [ "$forward" = 0 ]; then
 		natloopback=0
 		unset forward_target forward_port
 	fi
 	# review
 	[ -n "$NATMAP_DEBUG" ] && {
-		local v ucivv="enable interval stun_server http_server comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward_mode forward_method natloopback forward_target forward_port"
+		local v ucivv="enable interval stun_server http_server comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward forward_mode natloopback forward_target forward_port"
 		for v in $ucivv; do eval "echo $1 $v=\'\$$v\'"; done # ash not support ${!v}
 	}
 	[ "$error" -gt 0 ] && return 1
