natmap: Add client refresh scripts
Signed-off-by: Anya Lin <hukk1996@gmail.com>

diff --git a/net/natmap/files/natmap.init b/net/natmap/files/natmap.init
--- a/net/natmap/files/natmap.init
+++ b/net/natmap/files/natmap.init
@@ -107,6 +107,12 @@ validate_section_natmap() {
 		'natloopback:bool:1' \
 		'forward_target:ipaddr(1)' \
 		'forward_port:port' \
+		'refresh:bool:0' \
+		'clt_script:file' \
+		'clt_scheme:or("http", "https"):http' \
+		'clt_web_port:and(port, min(1))' \
+		'clt_username:string' \
+		'clt_password:string' \
 		'custom_script:file'
 }
 
@@ -155,6 +161,10 @@ natmap_instance() {
 	procd_set_param env "SECTIONID=$1"
 	if [ "$forward" = 1 -a "$forward_port" = 0 ]; then
 		[ "$forward_mode" = "dnat" ] && procd_append_param env "RWFW=1"
+		if [ "$refresh" = 1 ]; then
+			procd_append_param env "REFRESH=$clt_script"
+			procd_append_param env "REFRESH_PARAM={\"scheme\":\"$clt_scheme\",\"web_port\":$clt_web_port,\"username\":\"$clt_username\",\"password\":\"$clt_password\",\"ip\":\"$forward_target\"}"
+		fi
 	fi
 
 	[ -n "${custom_script}" ] && procd_append_param env "CUSTOM_SCRIPT=${custom_script}"
@@ -245,6 +255,7 @@ launcher() {
 	esac
 	[ -z "$bind_ip" ] && >&2 echo "$(basename $0): section $1 bind_ip parsing failed, there may be no $family network connection" && let error++
 	[ -z "$port" ] && err_msg__empty $1 port && let error++
+	## forward
 	if   [ "$forward" = 1 ]; then
 		[ "$forward_mode" = "dnat" -a "$family" = "ipv6" ] && >&2 echo "$(basename $0): section $1 option forward_mode 'dnat' not support under IPv6" && let error++
 		[ "$forward_mode" != "dnat" ] && natloopback=0
@@ -264,9 +275,17 @@ launcher() {
 		natloopback=0
 		unset forward_target forward_port
 	fi
+	## refresh
+	if   [ "$refresh" = 1 ]; then
+		[ -x "$clt_script" ] || { >&2 echo "$(basename $0): section $1 option clt_script '$clt_script' is empty or non-executable"; let error++; }
+		[ -z "$clt_web_port" ] && err_msg__empty $1 clt_web_port && let error++
+	elif [ "$refresh" = 0 ]; then
+		unset clt_script
+	fi
+
 	# review
 	[ -n "$NATMAP_DEBUG" ] && {
-		local v ucivv="enable interval stun_server http_server comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward forward_mode natloopback forward_target forward_port custom_script"
+		local v ucivv="enable interval stun_server http_server comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward forward_mode natloopback forward_target forward_port refresh clt_script clt_scheme clt_web_port clt_username clt_password custom_script"
 		for v in $ucivv; do eval "echo $1 $v=\'\$$v\'"; done # ash not support ${!v}
 	}
 	[ "$error" -gt 0 ] && return 1
